mybatis:
  #扫描所有类路径下的Mapper.xml
  mapper-locations: classpath*:Mapper/**/*Mapper.xml
  #指定实体类的包名
  type-aliases-package: com.mypro.**.domain
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

spring:
  #设置springSession
  session:
    store-type: redis
    #设置过期时间
    timeout: 10800
  redis:
    #lettuce配置
    lettuce:
      pool:
        max-active: 8 #最大连接数 默认为8
        max-idle: 8 #最大空闲连接数 默认为8
        min-idle: 0 #最小空闲连接数 默认为0
    #使用哨兵模式
    sentinel:
      master: mymaster
      nodes:
      password:
  thymeleaf:
    #关闭thymeleaf缓存
    cache: false
  jackson:
    #设置dateFormat的转换格式
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mypro?useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #druid连接池配置
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      #开启页面状态过滤器，用于采集web-jdbc关联监控的数据
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        #开启监控视图
        enabled: true
        #允许名单，不填为全允许
        allow:
        #监控视图的账户和密码
        login-username:
        login-password:
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true
          # 慢SQL记录,超过一秒会记录，这里是关闭状态
          log-slow-sql: false
          slow-sql-millis: 1000
  #配置rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456
    virtual-host: /vhost_test
    #开启生产者消息确认
    publisher-confirm-type: correlated
    #开启生产者消息是否分发到队列回调，只有发送到队列失败时，才会触发回调
    publisher-returns: true
    template:
      #设置开启后，会强制回调，不管是否发送失败
      mandatory: true
    listener:
      simple:
        #监听器调用程序线程的最大数量
        max-concurrency: 15
        #监听器调用程序线程的最小数量
        concurrency: 5
        #每个消费者未完成的最大未确认消息数
        prefetch: 10
  #配置邮件发送
  mail:
    host: smtp.126.com
    username: houhaotong@126.com
    password:
#自己的rabbitmq所需的配置
mq:
  myrabbit:
    #邮件发送消息模型
    email:
      queue: seckill.email.queue
      exchange: seckill.email.exchange
      routing-key: seckill.email.routingKey
    #死信消息模型
    dead:
      queue: seckill.dead.queue
      exchange: seckill.dead.exchange
      routing-key: seckill.dead.routingKey
    #设置过期时间
    expire: 1800000
#邮件信息设置
seckill:
  mail:
    send-from: houhaotong@126.com
    subject: 商品抢购成功
    content: 您好，您已成功抢购到商品：%s,复制该链接到浏览器打开，查看抢购订单详情：http://localhost:8088/seckill/order/%s,并在1小时内支付订单，否则将会取消订单。
    send-to: 495733684@qq.com